services:
  authservice:
    image: authservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=database;Database=AuthServiceDb;User Id=sa;Password=Alexwhite96#
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Alexwhite96#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
